baseurl: "/ap" # the subpath of your site, e.g. /blog
url: "https://candib80.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

plugins:
  - jekyll-remote-theme

remote_theme: candib80/jekyll-theme-cs50

title: CS50 AP
